# Generated by Django 5.2.17 on 2026-08-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
