# Generated by Django 5.2.17 on 2026-08-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_department_available_beds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='number_of_doctors',
        ),
    ]
